routes/web.php
<?php

/*
 |--------------------------------------------------------------------------
 | Web Routes
 |--------------------------------------------------------------------------
 |
 | Here is where you can register web routes for your application. These
 | routes are loaded by the RouteServiceProvider within a group which
 | contains the "web" middleware group. Now create something great!
 |
 */

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/support', function () {
    return view('support');
})->name('support');

Route::get('/ibpay', function () {
    return view('ibpay.index');
})->name('ibpay');

Route::get('/zestview', function () {
    return view('zestview.index');
})->name('zestview');

Route::get('/insurance', function () {
    return view('insurance.index');
})->name('insurance');

Route::get('/knowledge', function () {
    return view('knowledge.index');
})->name('knowledge');

Route::get('/storeSales', function () {
    return view('storeSales.index');
})->name('storeSales');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('check','HomeController@check')->name('check');
Route::post('storeOwners/checkCustomer','StoreOwnerController@checkCustomer')->name('checkCustomer');
Route::post('storeOwners/submitTicket','StoreOwnerController@submitTicket')->name('submitTicket');

Route::post('storeOnboarding/processtoken', 'StoreOnboardingController@processToken');
Route::resource('storeOnboarding', 'StoreOnboardingController');

Route::post('loanyantra/checkCustomerLoans','LoanyantraController@checkCustomerLoans')->name('checkCustomerLoans');
Route::post('loanyantra/storeCustomer','LoanyantraController@storeCustomer')->name('storeCustomer');
Route::resource('loanyantra', 'LoanyantraController');

Route::post('nosales', 'CustomerController@nosales')->name('nosales');
Route::resource('storeOwners', 'StoreOwnerController');
Route::resource('customers', 'CustomerController');

Route::get('sale/{filter}','SaleController@filter')->name('salefilter');

Route::resource('sales', 'SaleController');
Route::resource('onboardings', 'OnboardingController');
Route::resource('userResponses', 'UserResponseController');

Route::get('download-excel-file/{type}','ReportController@downloadExcelFile')->name('excel-file');
Route::get('download-latest/{type}','ReportController@lastRecords')->name('excel');
Route::get('report/{filter}','ReportController@filter')->name('filter');

Route::resource('reports', 'ReportController');
Route::resource('orders', 'orderController');
Route::resource('wydr','WydrController');
Route::resource('medlife','MedlifeController');
Route::resource('zestmoney','ZestMoneyController');
Route::resource('onemg','OnemgController');

Route::get('customersales/{filter}', 'CustomerController@salesfilter')->name('customersales');

Route::get('order/{filter}','orderController@filter')->name('orderfilter');
Route::get('wydrsales/{filter}','WydrController@filter')->name('wydrfilter');
Route::get('medlifesales/{filter}','MedlifeController@filter')->name('medlifefilter');
Route::get('zestmoneysales/{filter}','ZestMoneyController@filter')->name('zestmoneyfilter');
Route::get('onemgsales/{filter}','OnemgController@filter')->name('onemgfilter');
Route::post('medlife/updateorder', 'MedlifeController@updateOrder');

Route::get('/migrations', function () {
    try {
        dump('Init with app tables migrations...');
        dump(Artisan::call( 'migrate', ['--step'=> ''] ));
        dump('Done with app tables migrations');
    } catch (Exception $e) {
        print_r($e->getMessage());
        Response::make($e->getMessage(), 500);
    }
});

Route::get('/validation', 'LoanyantraController@getLoginCredentials');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/customersales/amazon.blade.php
<table class="table table-responsive" id="sales-table">
    <thead>

        <th>Customer Name</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Paid</th>
        <th>Balance</th>
        <th>Date & Time</th>
        @if(Auth::user()->role=='storeowner')
        <th colspan="3">Action</th>
            @endif
    </thead>
    <tbody>
    @foreach($amazon_sales as $sale)
        <tr>
            <td>{!! $sale->customer_name !!}</td>
            <td>{!! $sale->product_name !!}</td>
            <td>{!! $sale->product_quantity !!}</td>
            <td>{!! $sale->price !!}</td>
            <td>{!! $sale->paid !!}</td>
            <td>{!! $sale->balance !!}</td>
            <td>{!! $sale->created_at->setTimezone(new DateTimeZone("Asia/Kolkata")) !!}</td>
            @if(Auth::user()->role=='storeowner')
            <td>
                {!! Form::open(['route' => ['sales.destroy', $sale->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('sales.edit', [$sale->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure you want to delete this order?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
                @endif
        </tr>
    @endforeach
    </tbody>
</table>

resources/views/customersales/index.blade.php
@extends('layouts.app')

@section('content')

    @if($amazon_sales->count() > 0)
    <section class="content-header">
        <h1>Amazon Sales</h1></section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('customersales.amazon')
                </div>
            </div>
        </div>
    </div>
    @endif

    @if($wydr_sales->count() > 0)
    <section class="content-header">
        <h1>Wydr Sales</h1></section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('customersales.wydr')
                </div>
            </div>
        </div>
    </div>
    @endif

    @if($onemg_sales->count() > 0)
    <section class="content-header">
        <h1>Medicines Sales</h1></section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('customersales.onemg')
                </div>
            </div>
        </div>
    </div>
    @endif

    @if($zestmoney_sales->count() > 0)
    <section class="content-header">
        <h1>ZestMoney Sales</h1></section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('customersales.zestmoney')
                </div>
            </div>
        </div>
    </div>
    @endif


@endsection

resources/views/customersales/onemg.blade.php
<table class="table table-responsive" id="sales-table">
    <thead>
    <th>Customer Name</th>
    <th>Order Id</th>
    <th>Price</th>
    <th>Paid</th>
    <th>Balance</th>
    <th>Date & Time</th>

    </thead>

    <tbody>
    @foreach($onemg_sales as $sale)
        <tr>
            <td>{!! $sale->customer_name !!}</td>
            <td>{!! $sale->order_id !!}</td>
            <td>{!! $sale->order_value !!}</td>
            <td>{!! $sale->paid !!}</td>
            <td>{!! $sale->balance !!}</td>
            <td>{!! $sale->created_at->setTimezone(new DateTimeZone("Asia/Kolkata")) !!}</td>
        </tr>
    @endforeach
    </tbody>

</table>

resources/views/customersales/wydr.blade.php
<table class="table table-responsive" id="sales-table">
    <thead>
        <th>Customer Name</th>
        <th>Product Name</th>
        <th>Order Id</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Shipping</th>
        <th>Total</th>
        <th>Paid</th>
        <th>Balance</th>
        <th>Date & Time</th>

    </thead>

    <tbody>
    @foreach($wydr_sales as $sale)
        <tr>
            <td>{!! $sale->customer_name !!}</td>
            <td>{!! $sale->product_name !!}</td>
            <td>{!! $sale->order_id !!}</td>
            <td>{!! $sale->quantity !!}</td>
            <td>{!! $sale->price !!}</td>
            <td>{!! $sale->shipping_cost !!}</td>
            <td>{!! $sale->total_cost !!}</td>
            <td>{!! $sale->paid !!}</td>
            <td>{!! $sale->balance !!}</td>
            <td>{!! $sale->created_at->setTimezone(new DateTimeZone("Asia/Kolkata")) !!}</td>
        </tr>
    @endforeach
    </tbody>

</table>

resources/views/customersales/zestmoney.blade.php
<table class="table table-responsive" id="sales-table">
    <thead>
        <th>Customer Name</th>
        <th>Product Name</th>
        <th>Order Id</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
        <th>Date & Time</th>

    </thead>

    <tbody>
    @foreach($zestmoney_sales as $sale)
        <tr>
            <td>{!! $sale->customer_name !!}</td>
            <td>{!! $sale->product_name !!}</td>
            <td>{!! $sale->order_id !!}</td>
            <td>{!! $sale->quantity !!}</td>
            <td>{!! $sale->price !!}</td>
            <td>{!! $sale->total_cost !!}</td>
            <td>{!! $sale->created_at->setTimezone(new DateTimeZone("Asia/Kolkata")) !!}</td>
        </tr>
    @endforeach
    </tbody>

</table>