routes/web.php
<?php

/*
 |--------------------------------------------------------------------------
 | Web Routes
 |--------------------------------------------------------------------------
 |
 | Here is where you can register web routes for your application. These
 | routes are loaded by the RouteServiceProvider within a group which
 | contains the "web" middleware group. Now create something great!
 |
 */

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/support', function () {
    return view('support');
})->name('support');

Route::get('/ibpay', function () {
    return view('ibpay.index');
})->name('ibpay');

Route::get('/zestview', function () {
    return view('zestview.index');
})->name('zestview');

Route::get('/insurance', function () {
    return view('insurance.index');
})->name('insurance');

Route::get('/knowledge', function () {
    return view('knowledge.index');
})->name('knowledge');

Route::get('/storeSales', function () {
    return view('storeSales.index');
})->name('storeSales');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('check','HomeController@check')->name('check');
Route::post('storeOwners/checkCustomer','StoreOwnerController@checkCustomer')->name('checkCustomer');
Route::post('storeOwners/submitTicket','StoreOwnerController@submitTicket')->name('submitTicket');

Route::post('storeOnboarding/processtoken', 'StoreOnboardingController@processToken');
Route::resource('storeOnboarding', 'StoreOnboardingController');

Route::post('loanyantra/checkCustomerLoans','LoanyantraController@checkCustomerLoans')->name('checkCustomerLoans');
Route::post('loanyantra/storeCustomer','LoanyantraController@storeCustomer')->name('storeCustomer');
Route::resource('loanyantra', 'LoanyantraController');

Route::post('nosales', 'CustomerController@nosales')->name('nosales');
Route::resource('storeOwners', 'StoreOwnerController');
Route::resource('customers', 'CustomerController');

Route::get('sale/{filter}','SaleController@filter')->name('salefilter');

Route::resource('sales', 'SaleController');
Route::resource('onboardings', 'OnboardingController');
Route::resource('userResponses', 'UserResponseController');

Route::get('download-excel-file/{type}','ReportController@downloadExcelFile')->name('excel-file');
Route::get('download-latest/{type}','ReportController@lastRecords')->name('excel');
Route::get('report/{filter}','ReportController@filter')->name('filter');

Route::resource('reports', 'ReportController');
Route::resource('orders', 'orderController');
Route::resource('wydr','WydrController');
Route::resource('medlife','MedlifeController');
Route::resource('zestmoney','ZestMoneyController');
Route::resource('onemg','OnemgController');

Route::get('customersales/{filter}', 'CustomerController@salesfilter')->name('customersales');

Route::get('order/{filter}','orderController@filter')->name('orderfilter');
Route::get('wydrsales/{filter}','WydrController@filter')->name('wydrfilter');
Route::get('medlifesales/{filter}','MedlifeController@filter')->name('medlifefilter');
Route::get('zestmoneysales/{filter}','ZestMoneyController@filter')->name('zestmoneyfilter');
Route::get('onemgsales/{filter}','OnemgController@filter')->name('onemgfilter');
Route::post('medlife/updateorder', 'MedlifeController@updateOrder');

Route::get('/migrations', function () {
    try {
        dump('Init with app tables migrations...');
        dump(Artisan::call( 'migrate', ['--step'=> ''] ));
        dump('Done with app tables migrations');
    } catch (Exception $e) {
        print_r($e->getMessage());
        Response::make($e->getMessage(), 500);
    }
});

Route::get('/validation', 'LoanyantraController@getLoginCredentials');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/StoreOwner.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\User;

/**
 * Class StoreOwner
 * @package App\Models
 * @version August 15, 2017, 5:32 am UTC
 *
 * @method static StoreOwner find($id=null, $columns = array())
 * @method static StoreOwner|\Illuminate\Database\Eloquent\Collection findOrFail($id, $columns = ['*'])
 * @property string name
 * @property string email
 * @property string password
 * @property date dob
 * @property string gender
 * @property string phone
 * @property string source
 * @property string amazon_store_id
 * @property string Previous_profession
 * @property string pan_number
 * @property string aadhar_number
 * @property string account_num
 * @property string onboarding_status
 */
class StoreOwner extends Model
{
    use SoftDeletes;

    public $table = 'store_owners';
    

    protected $dates = ['deleted_at'];


    public $fillable = [
    'id',

        'email',

        'dob',
        'gender',
        'phone',
        'source',
        'amazon_store_id',
        'Previous_profession',
        'pan_number',
        'aadhar_number',
        'account_num',
        'onboarding_status',
        'url'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [

        'email' => 'string',

        'dob' => 'date',
        'gender' => 'string',
        'phone' => 'string',
        'source' => 'string',
        'amazon_store_id' => 'string',
        'Previous_profession' => 'string',
        'pan_number' => 'string',
        'aadhar_number' => 'string',
        'account_num' => 'string',
        'onboarding_status' => 'string',
        'url'=>'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        /*'email' => 'required',,*/
        'dob' => 'required',
       /* 'gender' => 'required',*/
        'phone' => 'required',
       /* 'source' => 'required',*/
       /* 'amazon_store_id' => 'required',
        'Previous_profession' => 'required',
        'pan_number' => 'required',
        'aadhar_number' => 'required',
        'account_num' => 'required',
        'onboarding_status' => 'required'*/
    ];

        public function user ()
        {
            return $this->belongsTo(User::class, 'id');
        }

        public function customer(){
            return $this->hasMany(Customer::class,'user_id');
        }
    
}

app/Http/Controllers/StoreOwnerController.php
<?php

namespace App\Http\Controllers;

use App\Criteria\LatestCriteria;
use App\Http\Requests\CreateStoreOwnerRequest;
use App\Http\Requests\UpdateStoreOwnerRequest;
use App\Models\StoreOwner;
use App\Repositories\CustomerRepository;
use App\Repositories\StoreOwnerRepository;
use App\Http\Controllers\AppBaseController;
use App\User;
use Illuminate\Http\Request;
use Flash;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Session;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class StoreOwnerController extends AppBaseController
{
    /** @var  StoreOwnerRepository */
    private $storeOwnerRepository;
    /**
     * @var CustomerRepository
     */
    private $customerRepository;

    public function __construct(StoreOwnerRepository $storeOwnerRepo, CustomerRepository $customerRepository)
    {
        $this->storeOwnerRepository = $storeOwnerRepo;
        $this->customerRepository = $customerRepository;
//        $this->authorizeResource(StoreOwner::class);
    }

    /**
     * Display a listing of the StoreOwner.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {

        $this->storeOwnerRepository->pushCriteria(new RequestCriteria($request));
        $this->storeOwnerRepository->pushCriteria(new LatestCriteria());
        $storeOwners = $this->storeOwnerRepository->paginate(15);

        return view('store_owners.index')
            ->with('storeOwners', $storeOwners);

    }

    /**
     * Show the form for creating a new StoreOwner.
     *
     * @return Response
     */
    public function create()
    {
      //$this->authorize('create');
        return view('store_owners.create');
    }

    /**
     * Store a newly created StoreOwner in storage.
     *
     * @param CreateStoreOwnerRequest $request
     *
     * @return Response
     */
    public function store(CreateStoreOwnerRequest $request)
    {
        $input = $request->all();

       // $input[ 'password' ] = rand ( 100000, 999999 );

        $user=User::create([
            'name'=>$input['name'],
            'email'=>$input['email'],
            'password'=>bcrypt($input['password']),
        ]);
        if($user){
            $input['id'] = $user->id;
            $storeOwner = $this->storeOwnerRepository->create($input);
        }


        Flash::success('Store Owner saved successfully.');

        return redirect(route('storeOwners.index'));
    }

    /**
     * Display the specified StoreOwner.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {

        $storeOwner = $this->storeOwnerRepository->findWithoutFail($id);

        if (empty($storeOwner)) {
            Flash::error('Store Owner not found');

            return redirect(route('storeOwners.index'));
        }

        return view('store_owners.show')->with('storeOwner', $storeOwner);
    }

    /**
     * Show the form for editing the specified StoreOwner.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $storeOwner = $this->storeOwnerRepository->findWithoutFail($id);

        if (empty($storeOwner)) {
            Flash::error('Store Owner not found');

            return redirect(route('storeOwners.index'));
        }

        return view('store_owners.edit')->with('storeOwner', $storeOwner);
    }

    /**
     * Update the specified StoreOwner in storage.
     *
     * @param  int              $id
     * @param UpdateStoreOwnerRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateStoreOwnerRequest $request)
    {
        $storeOwner = $this->storeOwnerRepository->findWithoutFail($id);

        if (empty($storeOwner)) {
            Flash::error('Store Owner not found');

            return redirect(route('storeOwners.index'));
        }

        $user=User::find($id);
        if($request->password==""){
            $user->update(['name'=>$request->name]);
        }else{
            $user->update([
                'name'=>$request->name,
                'password'=>$request->password,
            ]);
        }
        $storeOwner = $this->storeOwnerRepository->update($request->all(), $id);

        Flash::success('Store Owner updated successfully.');
        return redirect(route('storeOwners.index'));
    }

    /**
     * Remove the specified StoreOwner from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $storeOwner = $this->storeOwnerRepository->findWithoutFail($id);

        if (empty($storeOwner)) {
            Flash::error('Store Owner not found');

            return redirect(route('storeOwners.index'));
        }

        $this->storeOwnerRepository->delete($id);

        Flash::success('Store Owner deleted successfully.');

        return redirect(route('storeOwners.index'));
    }

    public function checkCustomer(Request $request)
    {
        $phone= $request->phone;
        $customer=$this->customerRepository->findByField('phone',$phone);
        //dd($customer->first()->id);
        if ($customer->isEmpty()){
            Session::put('phone',$phone);
            return redirect(route('customers.create'));
        }
        Session::put('c_id',$customer->first()->id);
        Session::put('c_name',$customer->first()->name);
        Session::put('c_phone',$customer->first()->phone);
        return redirect(route('sales.create'))->with('customer',$customer);
    }

    public function submitTicket(Request $request)
    {
	$store = $request->store;
	$issue = $request->issue;
    	$description = $request->description;
    	$name = Auth::user()->name;
    	$email = Auth::user()->email;
    	$subject = $store . " | " . $issue;

    	$url = 'https://ibpixel.freshdesk.com/api/v2/tickets';
    	$body = json_encode(array("description" => $description,
									"email" => $email,
									"name" => $name,
									"subject" => $subject,
									"priority" => 1,
									"status" => 2,
									"type" => $store));
#    								"custom_fields" => array("cf_store" => $store, "cf_category" => $issue)
    	
    	$headers = ["Content-Type: application/json"];
    	
    	$ch = curl_init( $url );
    	curl_setopt( $ch, CURLOPT_POST, 1);
    	curl_setopt( $ch, CURLOPT_POSTFIELDS, $body);
    	curl_setopt( $ch, CURLOPT_FOLLOWLOCATION, 1);
    	curl_setopt( $ch, CURLOPT_HTTPHEADER, $headers);
    	curl_setopt( $ch, CURLOPT_RETURNTRANSFER, 1);
    	curl_setopt( $ch, CURLOPT_USERPWD, "7ACu7Qnl8iOuEjwAyz9:X"); /* sindhu_api_key:X */
    	
    	$response = curl_exec( $ch );
    	
    	curl_close($ch);
    	
    	Flash::success('Ticket submitted successfully.');
    	
    	echo "<script type='text/javascript'>alert('Ticket submitted successfully.');</script>";
    	
    	return view('home');
    }
}

resources/views/store_owners/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Store Owner
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'storeOwners.store']) !!}

                        @include('store_owners.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/store_owners/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Store Owner
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($storeOwner, ['route' => ['storeOwners.update', $storeOwner->id], 'method' => 'patch']) !!}

                        @include('store_owners.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/store_owners/fields.blade.php
@if(mode('edit'))
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', $storeOwner->user->name, ['class' => 'form-control']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('password', 'Password:') !!}
    {!! Form::text('password', null, ['class' => 'form-control','placeholder'=>'Leave blank for no change']) !!}
</div>

@else
    <!-- Name Field -->
    <div class="form-group col-sm-6">
        {!! Form::label('name', 'Name:') !!}
        {!! Form::text('name', null, ['class' => 'form-control']) !!}
    </div>

    <div class="form-group col-sm-6">
        {!! Form::label('password', 'Password:') !!}
        {!! Form::text('password', null, ['class' => 'form-control']) !!}
    </div>
    @endif
<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control']) !!}
</div>

{{--<!-- Password Field -->
<div class="form-group col-sm-6">
    {!! Form::label('password', 'Password:') !!}
    {!! Form::password('password', ['class' => 'form-control']) !!}
</div>--}}

<!-- Dob Field -->
<div class="form-group col-sm-6">
    {!! Form::label('dob', 'Dob:') !!}
    {!! Form::date('dob', null, ['class' => 'form-control']) !!}
</div>

<!-- Gender Field -->
<div class="form-group col-sm-6">
    {!! Form::label('gender', 'Gender:') !!}
    {!! Form::text('gender', null, ['class' => 'form-control']) !!}
</div>

<!-- Phone Field -->
<div class="form-group col-sm-6">
    {!! Form::label('phone', 'Phone:') !!}
    {!! Form::text('phone', null, ['class' => 'form-control']) !!}
</div>

<!-- Source Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('source', 'Source:') !!}
    {!! Form::textarea('source', null, ['class' => 'form-control']) !!}
</div>

<!-- Amazon Store Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('amazon_store_id', 'Amazon Store Id:') !!}
    {!! Form::text('amazon_store_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Previous Profession Field -->
<div class="form-group col-sm-6">
    {!! Form::label('Previous_profession', 'Previous Profession:') !!}
    {!! Form::text('Previous_profession', null, ['class' => 'form-control']) !!}
</div>

<!-- Pan Number Field -->
<div class="form-group col-sm-6">
    {!! Form::label('pan_number', 'Pan Number:') !!}
    {!! Form::text('pan_number', null, ['class' => 'form-control']) !!}
</div>

<!-- Aadhar Number Field -->
<div class="form-group col-sm-6">
    {!! Form::label('aadhar_number', 'Aadhar Number:') !!}
    {!! Form::text('aadhar_number', null, ['class' => 'form-control']) !!}
</div>

<!-- Account Num Field -->
<div class="form-group col-sm-6">
    {!! Form::label('account_num', 'Account Num:') !!}
    {!! Form::text('account_num', null, ['class' => 'form-control']) !!}
</div>

{{--<!-- Onboarding Status Field -->
<div class="form-group col-sm-6">
    {!! Form::label('onboarding_status', 'Onboarding Status:') !!}
    {!! Form::text('onboarding_status', null, ['class' => 'form-control']) !!}
</div>--}}

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('storeOwners.index') !!}" class="btn btn-default">Cancel</a>
</div>

resources/views/store_owners/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Store Owners</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('storeOwners.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('store_owners.table')
            </div>
        </div>
    </div>
@endsection

resources/views/store_owners/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Store Owner
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('store_owners.show_fields')
                    @if(user()->role=='admin')

                    <a href="{!! route('storeOwners.index') !!}" class="btn btn-default">Back</a>
                    @else
                        <a href="{!! route('home') !!}" class="btn btn-default">Back</a>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/store_owners/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $storeOwner->user->id !!}</p>
</div>

<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{!! $storeOwner->user->name !!}</p>
</div>

<!-- Email Field -->
<div class="form-group">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $storeOwner->email !!}</p>
</div>

{{--<!-- Password Field -->
<div class="form-group">
    {!! Form::label('password', 'Password:') !!}
    <p>{!! $storeOwner->password !!}</p>
</div>--}}

<!-- Dob Field -->
<div class="form-group">
    {!! Form::label('dob', 'Dob:') !!}
    <p>{!! $storeOwner->dob !!}</p>
</div>

<!-- Gender Field -->
<div class="form-group">
    {!! Form::label('gender', 'Gender:') !!}
    <p>{!! $storeOwner->gender !!}</p>
</div>

<!-- Phone Field -->
<div class="form-group">
    {!! Form::label('phone', 'Phone:') !!}
    <p>{!! $storeOwner->phone !!}</p>
</div>

<!-- Source Field -->
<div class="form-group">
    {!! Form::label('source', 'Source:') !!}
    <p>{!! $storeOwner->source !!}</p>
</div>

<!-- Amazon Store Id Field -->
<div class="form-group">
    {!! Form::label('amazon_store_id', 'Amazon Store Id:') !!}
    <p>{!! $storeOwner->amazon_store_id !!}</p>
</div>

<!-- Previous Profession Field -->
<div class="form-group">
    {!! Form::label('Previous_profession', 'Previous Profession:') !!}
    <p>{!! $storeOwner->Previous_profession !!}</p>
</div>

<!-- Pan Number Field -->
<div class="form-group">
    {!! Form::label('pan_number', 'Pan Number:') !!}
    <p>{!! $storeOwner->pan_number !!}</p>
</div>

<!-- Aadhar Number Field -->
<div class="form-group">
    {!! Form::label('aadhar_number', 'Aadhar Number:') !!}
    <p>{!! $storeOwner->aadhar_number !!}</p>
</div>

<!-- Account Num Field -->
<div class="form-group">
    {!! Form::label('account_num', 'Account Num:') !!}
    <p>{!! $storeOwner->account_num !!}</p>
</div>

<!-- Onboarding Status Field -->
<div class="form-group">
    {!! Form::label('onboarding_status', 'Onboarding Status:') !!}
    <p>{!! $storeOwner->onboarding_status !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $storeOwner->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $storeOwner->updated_at !!}</p>
</div>

resources/views/store_owners/table.blade.php
<table class="table table-responsive" id="storeOwners-table">
    <thead>
    <th>Id</th>
        <th>Name</th>
        <th>Email</th>
        <th>Dob</th>
        <th>Gender</th>
        <th>Phone</th>
        <th>Source</th>
        <th>Amazon Store Id</th>
        <th>Previous Profession</th>
        <th>Pan Number</th>
        <th>Aadhar Number</th>
        <th>Account Num</th>
        <th>Onboarding Status</th>
        <th colspan="3">Action</th>
    </thead>
    <tbody>
    @foreach($storeOwners as $storeOwner)
        <tr>
            <td>{!! $storeOwner->user->id !!}</td>
            <td>{!! $storeOwner->user->name !!}</td>
            <td>{!! $storeOwner->email !!}</td>
            <td>{!! $storeOwner->dob !!}</td>
            <td>{!! $storeOwner->gender !!}</td>
            <td>{!! $storeOwner->phone !!}</td>
            <td>{!! $storeOwner->source !!}</td>
            <td>{!! $storeOwner->amazon_store_id !!}</td>
            <td>{!! $storeOwner->Previous_profession !!}</td>
            <td>{!! $storeOwner->pan_number !!}</td>
            <td>{!! $storeOwner->aadhar_number !!}</td>
            <td>{!! $storeOwner->account_num !!}</td>
            <td>{!! $storeOwner->onboarding_status !!}</td>
            <td>
                {!! Form::open(['route' => ['storeOwners.destroy', $storeOwner->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('storeOwners.show', [$storeOwner->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('storeOwners.edit', [$storeOwner->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>
{!! $storeOwners->links() !!}

resources/views/store_owners/videos.blade.php
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
        <div class="row">
            {!! Form::open(['route'=>'check']) !!}
            {{--<iframe width="854" height="480" src="https://www.youtube.com/embed/_3FiPmgqZd0" frameborder="0" allowfullscreen></iframe>--}}
            {{--{!! dd($videos) !!}--}}
            {{--@if($videos->first()==$video)--}}
                <iframe width="854" height="480" src="https://www.youtube.com/embed/{{$videos->first()->url}}" frameborder="0" allowfullscreen>
                </iframe>
            <input type="hidden" name="video_url" value="{{$videos->first()->url}}">
            {{--{!! Form::text('video_url',$videos->first()->url) !!}--}}
            {{--@endif--}}


            @foreach($videos as $video)

            <div class="form-group">
                {!!$video->question !!}
            </div>

                <div class="form-group">
                    {!!Form::radio('option.'.$video->id, $video->option_1); !!}
                    {!! Form::label('option.'.$video->id, $video->option_1) !!}
                </div>
                <div class="form-group">
                    {!!Form::radio('option.'.$video->id, $video->option_2); !!}
                    {!! Form::label('option.'.$video->id, $video->option_2) !!}
                </div>
                <div class="form-group">
                    {!!Form::radio('option.'.$video->id, $video->option_3); !!}
                    {!! Form::label('option.'.$video->id, $video->option_3) !!}
                </div>
                <div class="form-group">
                    {!!Form::radio('option.'.$video->id, $video->option_4); !!}
                    {!! Form::label('option.'.$video->id, $video->option_4) !!}
                </div>



                @endforeach
            <div class="form-group col-sm-12">
                {!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!}
            </div>
            {!! Form::close() !!}
        </div>
            </div>
        </div>
    </div>