routes/web.php
<?php

/*
 |--------------------------------------------------------------------------
 | Web Routes
 |--------------------------------------------------------------------------
 |
 | Here is where you can register web routes for your application. These
 | routes are loaded by the RouteServiceProvider within a group which
 | contains the "web" middleware group. Now create something great!
 |
 */

Route::get('/', function () {
    return view('auth.login');
});

Route::get('/support', function () {
    return view('support');
})->name('support');

Route::get('/ibpay', function () {
    return view('ibpay.index');
})->name('ibpay');

Route::get('/zestview', function () {
    return view('zestview.index');
})->name('zestview');

Route::get('/insurance', function () {
    return view('insurance.index');
})->name('insurance');

Route::get('/knowledge', function () {
    return view('knowledge.index');
})->name('knowledge');

Route::get('/storeSales', function () {
    return view('storeSales.index');
})->name('storeSales');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::post('check','HomeController@check')->name('check');
Route::post('storeOwners/checkCustomer','StoreOwnerController@checkCustomer')->name('checkCustomer');
Route::post('storeOwners/submitTicket','StoreOwnerController@submitTicket')->name('submitTicket');

Route::post('storeOnboarding/processtoken', 'StoreOnboardingController@processToken');
Route::resource('storeOnboarding', 'StoreOnboardingController');

Route::post('loanyantra/checkCustomerLoans','LoanyantraController@checkCustomerLoans')->name('checkCustomerLoans');
Route::post('loanyantra/storeCustomer','LoanyantraController@storeCustomer')->name('storeCustomer');
Route::resource('loanyantra', 'LoanyantraController');

Route::post('nosales', 'CustomerController@nosales')->name('nosales');
Route::resource('storeOwners', 'StoreOwnerController');
Route::resource('customers', 'CustomerController');

Route::get('sale/{filter}','SaleController@filter')->name('salefilter');

Route::resource('sales', 'SaleController');
Route::resource('onboardings', 'OnboardingController');
Route::resource('userResponses', 'UserResponseController');

Route::get('download-excel-file/{type}','ReportController@downloadExcelFile')->name('excel-file');
Route::get('download-latest/{type}','ReportController@lastRecords')->name('excel');
Route::get('report/{filter}','ReportController@filter')->name('filter');

Route::resource('reports', 'ReportController');
Route::resource('orders', 'orderController');
Route::resource('wydr','WydrController');
Route::resource('medlife','MedlifeController');
Route::resource('zestmoney','ZestMoneyController');
Route::resource('onemg','OnemgController');

Route::get('customersales/{filter}', 'CustomerController@salesfilter')->name('customersales');

Route::get('order/{filter}','orderController@filter')->name('orderfilter');
Route::get('wydrsales/{filter}','WydrController@filter')->name('wydrfilter');
Route::get('medlifesales/{filter}','MedlifeController@filter')->name('medlifefilter');
Route::get('zestmoneysales/{filter}','ZestMoneyController@filter')->name('zestmoneyfilter');
Route::get('onemgsales/{filter}','OnemgController@filter')->name('onemgfilter');
Route::post('medlife/updateorder', 'MedlifeController@updateOrder');

Route::get('/migrations', function () {
    try {
        dump('Init with app tables migrations...');
        dump(Artisan::call( 'migrate', ['--step'=> ''] ));
        dump('Done with app tables migrations');
    } catch (Exception $e) {
        print_r($e->getMessage());
        Response::make($e->getMessage(), 500);
    }
});

Route::get('/validation', 'LoanyantraController@getLoginCredentials');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Models/Sale.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Sale
 * @package App\Models
 * @version August 15, 2017, 8:14 am UTC
 *
 * @method static Sale find($id=null, $columns = array())
 * @method static Sale|\Illuminate\Database\Eloquent\Collection findOrFail($id, $columns = ['*'])
 * @property UnsignedInteger customer_id
 * @property string customer_name
 * @property string product_name
 * @property string product_id
 * @property string product_quantity
 * @property double price
 * @property boolean paid
 * @property double balance
 * @property date date
 */
class Sale extends Model
{
    use SoftDeletes;

    public $table = 'sales';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'amazon_store_id',
        'customer_id',
        'customer_name',
        'product_name',
        'product_id',
        'product_quantity',
        'price',
        'paid',
        'balance',
        'date'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'product_name' => 'string',
        'product_id' => 'string',
        'product_quantity' => 'string',
        'price' => 'double',
        'paid' => 'double',
        'balance' => 'double',
        'date' => 'date'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'product_name' => 'required',
        'product_id' => 'required',
        'product_quantity' => 'required',
        'price' => 'required'
    ];


}

app/Http/Controllers/SaleController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateSaleRequest;
use App\Http\Requests\UpdateSaleRequest;
use App\Models\Sale;
use App\Repositories\SaleRepository;
use App\Http\Controllers\AppBaseController;
use App\Repositories\StoreOwnerRepository;
use Carbon\Carbon;
use DateTimeZone;
use Illuminate\Http\Request;
use Flash;
use Illuminate\Support\Facades\Auth;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class SaleController extends AppBaseController
{
    /** @var  SaleRepository */
    private $saleRepository;
    private $storeOwnerRepository;

    public function __construct(SaleRepository $saleRepo, StoreOwnerRepository $storeOwnerRepository)
    {
        $this->saleRepository = $saleRepo;
        $this->storeOwnerRepository = $storeOwnerRepository;
    }

    /**
     * Display a listing of the Sale.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->saleRepository->pushCriteria(new RequestCriteria($request));
        if (Auth::user()-> role == 'admin') {
          $sales = $this->saleRepository->paginate(15);
        }else {
          $id = Auth::user()->id;
          $storeowner = $this->storeOwnerRepository->find($id);
          $sales = Sale::where(['amazon_store_id'=>$storeowner->amazon_store_id])->paginate(10);
        }
        return view('sales.index')
            ->with('sales', $sales);
    }

    /**
     * Show the form for creating a new Sale.
     *
     * @return Response
     */
    public function create()
    {
        return view('sales.create');
    }

    /**
     * Store a newly created Sale in storage.
     *
     * @param CreateSaleRequest $request
     *
     * @return Response
     */
    public function store(CreateSaleRequest $request)
    {
        $input = $request->all();
        $store_owner = $this->storeOwnerRepository->findWithoutFail(Auth::user()->id);
      //  dd($store_owner);
        $input['amazon_store_id'] = $store_owner->amazon_store_id;

        
        
        $sale = $this->saleRepository->create($input);

        Flash::success('Sale saved successfully.');

        return redirect(route('sales.index'));
    }

    /**
     * Display the specified Sale.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $sale = $this->saleRepository->findWithoutFail($id);

        if (empty($sale)) {
            Flash::error('Sale not found');

            return redirect(route('sales.index'));
        }

        return view('sales.show')->with('sale', $sale);
    }

    /**
     * Show the form for editing the specified Sale.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $sale = $this->saleRepository->findWithoutFail($id);

        if (empty($sale)) {
            Flash::error('Sale not found');

            return redirect(route('sales.index'));
        }

        return view('sales.edit')->with('sale', $sale);
    }

    /**
     * Update the specified Sale in storage.
     *
     * @param  int              $id
     * @param UpdateSaleRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSaleRequest $request)
    {
        $sale = $this->saleRepository->findWithoutFail($id);

        if (empty($sale)) {
            Flash::error('Sale not found');

            return redirect(route('sales.index'));
        }

        $sale = $this->saleRepository->update($request->all(), $id);

        Flash::success('Sale updated successfully.');

        return redirect(route('sales.index'));
    }

    /**
     * Remove the specified Sale from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $sale = $this->saleRepository->findWithoutFail($id);

        if (empty($sale)) {
            Flash::error('Sale not found');

            return redirect(route('sales.index'));
        }

        $this->saleRepository->delete($id);

        Flash::success('Sale deleted successfully.');

        return redirect(route('sales.index'));
    }

    private function isValidDate($date_str) {
        if (preg_match("/^[0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])$/",$date_str)) {
            return true;
        } else {
            return false;
        }
    }

    public function filter($filter){
        // This is needed to display as per IST and query as per UTC
        $utc_today = Carbon::today(new DateTimeZone('Asia/Kolkata'))->setTimezone(new DateTimeZone("UTC"));
        $utc_yesterday = Carbon::yesterday(new DateTimeZone('Asia/Kolkata'))->setTimezone(new DateTimeZone("UTC"));
        switch($filter){
            case 'today':
                if(Auth::user()->role=='admin'){
                    $reports = Sale::where('created_at', '>=', $utc_today)->paginate(10);
                }else{
                    $id=Auth::user()->id;
                    $storeowner=$this->storeOwnerRepository->find($id);
                    $reports=Sale::where([['created_at', '>=', $utc_today],
                                          ['amazon_store_id', '=', $storeowner->amazon_store_id]])->paginate(10);
                }
                return view('sales.index')
                    ->with('sales', $reports);
                break;
            case 'yesterday':
                if(Auth::user()->role=='admin'){
                    $reports = Sale::where([['created_at', '>=', $utc_yesterday],
                                            ['created_at', '<', $utc_today]])->paginate(10);
                }else{
                    $id=Auth::user()->id;
                    $storeowner=$this->storeOwnerRepository->find($id);
                    $reports=Sale::where([['created_at', '>=', $utc_yesterday],
                                          ['created_at', '<', $utc_today],
                                          ['amazon_store_id', '=', $storeowner->amazon_store_id]])->paginate(10);
                }
                return view('sales.index')
                    ->with('sales', $reports);
                break;
            case 'week':
                if(Auth::user()->role=='admin'){
                    $reports = Sale::where('created_at', '>=', $utc_today->subWeek())->paginate(10);
                }else{
                    $id=Auth::user()->id;
                    $storeowner=$this->storeOwnerRepository->find($id);
                    $reports=Sale::where([['created_at', '>=', $utc_today->subWeek()],
                                          ['amazon_store_id', '=', $storeowner->amazon_store_id]])->paginate(10);
                }
                return view('sales.index')
                    ->with('sales', $reports);
                break;
            case 'month':
                if(Auth::user()->role=='admin'){
                    $reports = Sale::where('created_at', '>=', $utc_today->subMonth())->paginate(10);
                }else{
                    $id=Auth::user()->id;
                    $storeowner=$this->storeOwnerRepository->find($id);
                    $reports=Sale::where([['created_at', '>=', $utc_today->subMonth()],
                                          ['amazon_store_id', '=', $storeowner->amazon_store_id]])->paginate(10);
                }
                return view('sales.index')
                    ->with('sales', $reports);
                break;
            default:
                list($date1, $date2) = explode(":", $filter);
                if (!$this->isValidDate($date1) || !$this->isValidDate($date2)) {
                    return redirect(route('sales.index'));
                }
                $date1 = Carbon::createFromFormat("Y-m-d H", trim($date1) . " 0");
                $date2 = Carbon::createFromFormat("Y-m-d H", trim($date2) . " 24");
                if(Auth::user()->role=='admin'){
                    $reports = Sale::where([['created_at', '>=', $date1],
                                            ['created_at', '<=', $date2]])->paginate(10);
                }else{
                    $id=Auth::user()->id;
                    $storeowner=$this->storeOwnerRepository->find($id);
                    $reports = Sale::where([['created_at', '>=', $date1],
                                          ['created_at', '<=', $date2],
                                          ['amazon_store_id', '=', $storeowner->amazon_store_id]])->paginate(10);
                }
                return view('sales.index')
                ->with('sales', $reports);
                break;
        }
    }
}

resources/views/sales/create.blade.php
@extends('layouts.app')

@section('content')
   {{-- @if(Session::has('customer'))
        $customer=Session::get('customer');--}}

        <section class="content-header">
        <h1>
            Select the sales entry
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="col-sm-3">
                    <button type="button" class="btn btn-block btn-warning" onclick="toggle_visibility('amazon')">Amazon Sales Entry</button>
                    <button type="button" class="btn btn-block btn-primary" onclick="toggle_visibility('wydr')">Wydr Sales Entry</button>
                    <!-- <button type="button" style=" background-color: #024b68; color:#ffffff;" class="btn btn-block" onclick="toggle_visibility('onemg')">Medicines Sales Entry</button> -->
                    <button type="button" class="btn btn-block btn-success" onclick="toggle_visibility('zestmoney')">ZestMoney Sales Entry</button>
                    <button type="button" class="btn btn-block btn-default" onclick="toggle_visibility('nosales')">No Sales</button>
                    <div class="clearfix"> <br> </div>
                </div>

            @if(Session::has('c_id'))

                <!-- Customer Name Field -->

                    <div class="form-group col-sm-6">
                        {!! Form::label('customer_name', 'Customer Name:') !!}
                        {!! Form::text('customer_name', Session::get('c_name'), ['class' => 'form-control','readonly']) !!}
                        <br>
                        <a href="{{ route('customersales',['type'=>Session::get('c_id')]) }}">Previous Orders of {{ Session::get('c_name') }}</a>
                        <div class="clearfix"> <br> </div>
                        <div class="form-group" id="nosales" style="display: none">
                            {!! Form::open(['route' => 'nosales']) !!}
                            {!! Form::text('customer_id', Session::get('c_id'), ['class' => 'form-control','style' => 'display:none']) !!}
                            {!! Form::text('customer_name', Session::get('c_name'), ['class' => 'form-control','style' => 'display:none']) !!}
                            {!! Form::label('reason_label', 'Reason for not buying:') !!}
						    {!! Form::select('reason', ['Did not find the required product' => 'Did not find the required product',
														'Just came to check the price' => 'Just came to check the price',
														'Found a lower price elsewhere' => 'Found a lower price elsewhere',
														'Stock not available' => 'Stock not available',
														'Not satisfied with the delivery time' => 'Not satisfied with the delivery time',
														'No trust in the product/service' => 'No trust in the product/service',
														'Still doing product research' => 'Still doing product research',
														'Other' => 'Other'], 1, ['class' => 'form-control']) !!}
							<br>
							{!! Form::submit('Submit', ['class' => 'btn btn-primary']) !!}
							{!! Form::close() !!}
                        </div>
                    </div>

                    </div>
                @endif
                 <div class="clearfix"></div>


                <div class="container">
                    <div class="row" id="amazon" style="display: none">
                        {!! Form::open(['route' => 'sales.store']) !!}
                        @include('sales.fields')

                        {!! Form::close() !!}
                    </div>

                    <div class="row" id="wydr" style="display: none">
                        {!! Form::open(['route' => 'wydr.store']) !!}
                        @include('wydr.fields')

                        {!! Form::close() !!}
                    </div>

                    <div class="row" id="onemg" style="display: none">
                        {!! Form::open(['route' => 'onemg.store']) !!}
                        @include('onemg.fields')

                        {!! Form::close() !!}
                    </div>

                    <div class="row" id="zestmoney" style="display: none">
                        {!! Form::open(['route' => 'zestmoney.store']) !!}
                        @include('zestmoney.fields')

                        {!! Form::close() !!}
                    </div>
                 </div>
            </div>
        </div>
    </div>
   {{-- @endif--}}
@endsection

@section('scripts')
    <script>
    function toggle_visibility(id) {
        var e = document.getElementById(id);
        if (id == 'amazon') {
          amazonCalc();
          document.getElementById('wydr').style.display = 'none';
          document.getElementById('onemg').style.display = 'none';
          document.getElementById('zestmoney').style.display = 'none';
          document.getElementById('nosales').style.display = 'none';
        }else if (id == 'wydr') {
          document.getElementById('amazon').style.display = 'none';
          document.getElementById('onemg').style.display = 'none';
          document.getElementById('zestmoney').style.display = 'none';
          document.getElementById('nosales').style.display = 'none';
        }else if(id == 'onemg') {
          document.getElementById('wydr').style.display = 'none';
          document.getElementById('amazon').style.display = 'none';
          document.getElementById('zestmoney').style.display = 'none';
          document.getElementById('nosales').style.display = 'none';
        }else if(id == 'zestmoney') {
            document.getElementById('wydr').style.display = 'none';
            document.getElementById('amazon').style.display = 'none';
            document.getElementById('onemg').style.display = 'none';
            document.getElementById('nosales').style.display = 'none';
        }else if(id == 'nosales') {
            document.getElementById('wydr').style.display = 'none';
            document.getElementById('amazon').style.display = 'none';
            document.getElementById('onemg').style.display = 'none';
            document.getElementById('zestmoney').style.display = 'none';
        }
        if (e.style.display == 'block' || e.style.display=='') e.style.display = 'none';
        else e.style.display = 'block';
    }

    function amazonCalc(){
        $(document).ready(function() {
            $('#paid').on('input', function() {
                if(document.getElementById('price').value) {
                    var value = document.getElementById('price').value;
                    var qty = document.getElementById('product_quantity').value;
                    var value1 = document.getElementById('paid').value;
                    var value2 = document.getElementById('balance');
                    value2.value = (value*qty) - value1;
                }else{
                    alert("Please Enter the price of product");
                    document.getElementById('balance').value = "";
                }
            });
            $('#price').on('input', function() {
                if(document.getElementById('price').value) {
                    var value = document.getElementById('price').value;
                    var qty = document.getElementById('product_quantity').value;
                    var value1 = document.getElementById('paid').value;
                    var value2 = document.getElementById('balance');
                    value2.value = (value*qty) - value1;
                }else{
//                    alert("Please Enter the price of product");
                    document.getElementById('balance').value = "";
                }
            });
            $('#product_quantity').on('input', function() {
                if(document.getElementById('price').value) {
                    var value = document.getElementById('price').value;
                    var qty = document.getElementById('product_quantity').value;
                    var value1 = document.getElementById('paid').value;
                    var value2 = document.getElementById('balance');
                    value2.value = (value*qty) - value1;
                }else{
//                    alert("Please Enter the price of product");
                    document.getElementById('balance').value = "";
                }
            });
        });
      }
    </script>
@endsection

resources/views/sales/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sale
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($sale, ['route' => ['sales.update', $sale->id], 'method' => 'patch']) !!}

                        @include('sales.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

@section('scripts')
    <script>
        $(document).ready(function() {
            $('#paid').on('input', function() {
                if(document.getElementById('price').value) {
                    var value = document.getElementById('price').value;
                    var qty = document.getElementById('product_quantity').value;
                    var value1 = document.getElementById('paid').value;
                    var value2 = document.getElementById('balance');
                    value2.value = (value*qty) - value1;
                }else{
                    alert("Please Enter the price of product");
                    document.getElementById('balance').value = "";
                }
            });
            $('#price').on('input', function() {
                if(document.getElementById('price').value) {
                    var value = document.getElementById('price').value;
                    var qty = document.getElementById('product_quantity').value;
                    var value1 = document.getElementById('paid').value;
                    var value2 = document.getElementById('balance');
                    value2.value = (value*qty) - value1;
                }else{
//                    alert("Please Enter the price of product");
                    document.getElementById('balance').value = "";
                }
            });
            $('#product_quantity').on('input', function() {
                if(document.getElementById('price').value) {
                    var value = document.getElementById('price').value;
                    var qty = document.getElementById('product_quantity').value;
                    var value1 = document.getElementById('paid').value;
                    var value2 = document.getElementById('balance');
                    value2.value = (value*qty) - value1;
                }else{
//                    alert("Please Enter the price of product");
                    document.getElementById('balance').value = "";
                }
            });
        });
    </script>
@endsection

resources/views/sales/fields.blade.php
@if(Session::has('c_id'))
<!-- Customer Id Field -->
<div class="form-group col-sm-6" style="display:none">
    {!! Form::label('customer_id', 'Customer Id:') !!}
    {!! Form::text('customer_id', Session::get('c_id'), ['class' => 'form-control','readonly']) !!}
</div>
<div class="form-group col-sm-6" style="display:none">
        {!! Form::label('customer_name', 'Customer Name:') !!}
        {!! Form::text('customer_name', Session::get('c_name'), ['class' => 'form-control','readonly']) !!}
</div>
@endif
<!-- Product Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('product_name', 'Product Name:') !!}
    {!! Form::text('product_name', null, ['class' => 'form-control']) !!}
</div>

<!-- Product Category Field -->
<div class="form-group col-sm-6"  style="display:none">
    {!! Form::label('product_category', 'Product Category:') !!}
    {!! Form::select('product_category', ['Mobiles' => 'Mobiles',
										  'Electronics' => 'Electronics',
										  'Electronic Accessories'=>'Electronic Accessories',
										  'Home Appliances'=>'Home Appliances',
										  'Groceries'=>'Groceries',
										  'Footwear'=>'Footwear',
										  'Clothing Accessories'=>'Clothing Accessories',
										  'Fashion'=>'Fashion',
										  'Sports, Fitness & Outdoors'=>'Sports, Fitness & Outdoors',
										  'Toys & Baby Products'=>'Toys & Baby Products',
										  'Beauty & Health'=>'Beauty & Health',
										  'Home & Kitchen'=>'Home & Kitchen',
										  'Other'=>'Other'], 1, ['class' => 'form-control']) !!}
</div>

<!-- Product Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('product_id', 'Order Id:') !!}
    {!! Form::text('product_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Product Quantity Field -->
<div class="form-group col-sm-6">
    {!! Form::label('product_quantity', 'Quantity:') !!}
    {!! Form::select('product_quantity', ['1' => '1', '2' => '2', '3'=>'3', '4'=>'4', '5'=>'5','6'=>'6','7'=>'7','8'=>'8','9'=>'9','10'=>'10'], 1, ['class' => 'form-control']) !!}
</div>

<!-- Price Field -->
<div class="form-group col-sm-6">
    {!! Form::label('price', 'Price:') !!}
    {!! Form::number('price', null, ['class' => 'form-control']) !!}
</div>

<!-- Paid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('paid', 'Paid:') !!}
    {!! Form::number('paid', null, ['class' => 'form-control']) !!}
</div>
<!-- Paid Field -->
<div class="form-group col-sm-6">
    {!! Form::label('balance', 'Balance:') !!}
    {!! Form::number('balance', null, ['class' => 'form-control', 'readonly']) !!}
</div>

<!-- Date Field -->
<div class="form-group col-sm-6" style="display:none">
    {!! Form::label('date', 'Date:') !!}
    {!! Form::datetime('date', \Carbon\Carbon::now(new DateTimeZone('Asia/Kolkata'))->format('Y-m-d H:m:s'), ['class' => 'form-control', 'readonly']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    @if(user()->role=="storeowner")
        <a href="{!! route('home') !!}" class="btn btn-default"> Cancel</a>
    @else
        <a href="{!! route('customers.index') !!}" class="btn btn-default">Cancel</a>
    @endif

</div>

resources/views/sales/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Amazon Sales</h1>
        <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px; margin-right: 5px" href="{{ route('salefilter',['type'=>'today']) }}">Today</a>
        <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px; margin-right: 5px" href="{{ route('salefilter',['type'=>'yesterday']) }}">Yesterday</a>
        <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px; margin-right: 5px" href="{{ route('salefilter',['type'=>'week']) }}">Last Week</a>
        <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px; margin-right: 5px" href="{{ route('salefilter',['type'=>'month']) }}">Last Month</a>
    </section>
    <div class="content">
        <div class="clearfix"></div>
        <div class="pull-right" style="padding:5px;width:100%;text-align:right;" >
            <label>From:</label><input type="date" id="from-date">
            <label>To:</label><input type="date" id="to-date">
            <a class="btn btn-primary" onclick="date_filter()">Filter</a>
        </div>
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('sales.table')
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script>
    function date_filter() {
        var from = document.getElementById("from-date").value;
        var to = document.getElementById("to-date").value;
        var filter = from + ":" + to;
        var url = "{{ route('salefilter',['type'=>':filter']) }}";
        url = url.replace(':filter', filter);
        document.location.href = url;
    }
    </script>

@endsection

resources/views/sales/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Sale
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('sales.show_fields')
                    <a href="{!! route('sales.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/sales/show_fields.blade.php
<!-- Product Name Field -->
<div class="form-group">
    {!! Form::label('product_name', 'Product Name:') !!}
    <p>{!! $sale->product_name !!}</p>
</div>

<!-- Product Quantity Field -->
<div class="form-group">
    {!! Form::label('product_quantity', 'Product Quantity:') !!}
    <p>{!! $sale->product_quantity !!}</p>
</div>

<!-- Price Field -->
<div class="form-group">
    {!! Form::label('price', 'Price:') !!}
    <p>{!! $sale->price !!}</p>
</div>

<!-- Paid Field -->
<div class="form-group">
    {!! Form::label('paid', 'Paid:') !!}
    <p>{!! $sale->paid !!}</p>
</div>

<!-- Balance Field -->
<div class="form-group">
    {!! Form::label('balance', 'Balance:') !!}
    <p>{!! $sale->balance !!}</p>
</div>

<!-- Date Field -->
<div class="form-group">
    {!! Form::label('date', 'Date:') !!}
    <p>{!! $sale->date !!}</p>
</div>